<Project Sdk="Godot.NET.Sdk/4.7.2">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Godot3dFighter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="src/Core/**;tests/**;tools/**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="src/Core/Core.csproj" />
  </ItemGroup>

</Project>
