using System;
using System.Globalization;
using System.IO;
using System.Text;

const int SinTableSize = 1024;
const int AtanTableSize = 257;

var root = args.Length > 0 ? args[0] : Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "src", "Core", "Math");
Directory.CreateDirectory(root);

WriteSinTable(Path.Combine(root, "SinTable.g.cs"));
WriteAtanTable(Path.Combine(root, "AtanTable.g.cs"));

static void WriteSinTable(string path)
{
    var values = new int[SinTableSize];
    for (var i = 0; i < SinTableSize; i++)
    {
        var radians = 2.0 * Math.PI * i / SinTableSize;
        values[i] = (int)Math.Round(Math.Sin(radians) * 65536.0, MidpointRounding.AwayFromZero);
    }

    WriteArrayFile(path, "SinTable", values);
}

static void WriteAtanTable(string path)
{
    var values = new int[AtanTableSize];
    for (var i = 0; i < AtanTableSize; i++)
    {
        var ratio = i / (double)(AtanTableSize - 1);
        var radians = Math.Atan(ratio);
        values[i] = (int)Math.Round(radians * 65536.0 / (2.0 * Math.PI), MidpointRounding.AwayFromZero);
    }

    WriteArrayFile(path, "AtanTable", values);
}

static void WriteArrayFile(string path, string name, int[] values)
{
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated>");
    sb.AppendLine("// このファイルはtools/GenTablesで生成される。手で編集しない。");
    sb.AppendLine("// </auto-generated>");
    sb.AppendLine();
    sb.AppendLine("namespace Godot3dFighter.Core.Math;");
    sb.AppendLine();
    sb.Append("internal static class ").Append(name).AppendLine();
    sb.AppendLine("{");
    sb.AppendLine("    internal static readonly int[] Values =");
    sb.AppendLine("    {");
    for (var i = 0; i < values.Length; i += 8)
    {
        var line = new StringBuilder("        ");
        var end = System.Math.Min(i + 8, values.Length);
        for (var j = i; j < end; j++)
        {
            line.Append(values[j].ToString(CultureInfo.InvariantCulture));
            line.Append(", ");
        }

        sb.AppendLine(line.ToString().TrimEnd());
    }

    sb.AppendLine("    };");
    sb.AppendLine("}");

    File.WriteAllText(path, sb.ToString());
}
