name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    permissions:
      contents: read
    uses: okamyuji/reusable-workflows/.github/workflows/dotnet-ci.yml@v1
    with:
      godot-sha512: "1855960b27ee3ef5e66e5e228cced69d55637b24334a7411162687dcd077d8f9f645348cdb8eae984bec8135d49ed855a1e3a16476786b8bce60774fd8402d13"
      mutation-score-threshold: 60

  security:
    permissions:
      contents: read
      pull-requests: write
    uses: okamyuji/reusable-workflows/.github/workflows/security-scan.yml@v1
